server:
  port: 8080 
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://fujikawamia.rwlb.rds.aliyuncs.com:3306/resources_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: xixixi
    password: Raiden2005@0720
    driver-class-name: com.mysql.cj.jdbc.Driver
  jp a:
    hibernate:
      ddl-auto: update 
   
